export const SET_PAGE_TITLE = 'APP/SET_PAGE_TITLE';
export const SET_PAGE_DESCRIPTION = 'APP/SET_PAGE_DESCRIPTION';
export const OPEN_DRAWER = 'APP/OPEN_DRAWER';
export const CLOSE_DRAWER = 'APP/CLOSE_DRAWER';
